/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;

import CapaNegocio.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luanz
 */
public class formulario extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public formulario() {
        initComponents();
        listarlibro();
        listarcliente();
        listarventa();
        jBgrabarVenta.setEnabled(false);
        jBgrabarlibro.setEnabled(false);
    }
     /**
     * funcion que crea la vista de la tabla libros en la aplicacion y le pone los elementos de la tabla de la base de datos
     */
    public void listarlibro(){
        DefaultTableModel tabla = new DefaultTableModel();
        DataLibro libro = new DataLibro();
        ArrayList<DataLibro> lista2 = new ArrayList();
        lista2 = libro.ListaLibro();
        tabla.addColumn("Codigo");
        tabla.addColumn("Titulo");
        tabla.addColumn("Autor");
        tabla.addColumn("Precio");
        tabla.setRowCount(lista2.size());
        int i=0;
        
        for(DataLibro x: lista2){
            tabla.setValueAt(x.getCodigo(), i, 0);
            tabla.setValueAt(x.getTitulo(), i, 1);
            tabla.setValueAt(x.getAutor(), i, 2);
            tabla.setValueAt(x.getPrecio(), i, 3);
            i++;
        }
        this.tablaLibros.setModel(tabla);
    }
    
     /**
     * funcion que crea la vista de la tabla en la aplicacion y le pone los elementos de la tabla de la base de datos
     */
    public void listarcliente(){
        DefaultTableModel tabla = new DefaultTableModel();
        DataCliente cliente = new DataCliente();
        ArrayList<DataCliente> lista2 = new ArrayList();
        lista2 = cliente.ListaCliente();
        tabla.addColumn("Id");
        tabla.addColumn("nombre");
        tabla.addColumn("Direccion");
        tabla.setRowCount(lista2.size());
        int i=0;
        
        for(DataCliente x: lista2){
            tabla.setValueAt(x.getId(), i, 0);
            tabla.setValueAt(x.getNombreCliente(), i, 1);
            tabla.setValueAt(x.getDireccion(), i, 2);
            i++;
        }
        this.tablaCliente.setModel(tabla);
    }
    
     /**
     * funcion que crea la vista de la tabla ventas en la aplicacion y le pone los elementos de la tabla de la base de datos
     */
    public void listarventa(){
        DefaultTableModel tabla = new DefaultTableModel();
        DataVenta venta = new DataVenta();
        ArrayList<DataVenta> lista2 = new ArrayList();
        lista2 = venta.ListaVenta();
        tabla.addColumn("Numero de venta");
        tabla.addColumn("Nombre del cliente");
        tabla.addColumn("Codigo del libro");
        tabla.addColumn("Total a pagar");
        tabla.setRowCount(lista2.size());
        int i=0;
        
        for(DataVenta x: lista2){
            tabla.setValueAt(x.getNumeroVenta(), i, 0);
            tabla.setValueAt(x.getNombreCliente(), i, 1);
            tabla.setValueAt(x.getCodigoLibro(), i, 2);
            tabla.setValueAt(x.getTotalPagar(), i, 3);
            i++;
        }
        this.tablaVentas.setModel(tabla);
    }
    
    /**
     * Funcion que pone en blanco todas las casillas de texto en la vista libro
     */
    public void limpiarCajasTextoL(){
        this.JTautorlibro.setText("");
        this.jTpreciolibro.setText("");
        this.jTcodigolibro.setText("");
        this.jTtitulolibro.setText("");
    }
    
    /**
     * Funcion que pone en blanco todas las casillas de texto en la vista cliente
     */
    public void limpiarCajasTextoC(){
        this.JTIdCliente.setText("");
        this.JTdireccionCliente.setText("");
        this.JTnombreCliente.setText("");
    }
    
    /**
     * Funcion que pone en blanco todas las casillas de texto en la vista venta
     */
    public void limpiarCajasTextoV(){
        this.jTCodigoLibrov.setText("");
        this.jTnombreCVenta.setText("");
        this.jTnombreCVenta.setText("");
        this.jTtotalPVenta.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jBnuevolibro = new javax.swing.JButton();
        jBgrabarlibro = new javax.swing.JButton();
        jBeliminarlibro = new javax.swing.JButton();
        jBmodificarlibro = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTcodigolibro = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTtitulolibro = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        JTautorlibro = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTpreciolibro = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCliente = new javax.swing.JTable();
        JBagregarCliente = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTIdCliente = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTnombreCliente = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        JTdireccionCliente = new javax.swing.JTextPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTnumeroVenta = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTnombreCVenta = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTCodigoLibrov = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTtotalPVenta = new javax.swing.JTextPane();
        jBnuevaVenta = new javax.swing.JButton();
        jBgrabarVenta = new javax.swing.JButton();
        JBmodificarVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("libros Disponibles:");

        tablaLibros.setBackground(new java.awt.Color(255, 255, 255));
        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaLibrosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaLibros);

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CODIGO:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("TITULO:");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("AUTOR:");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("PRECIO:");

        jBnuevolibro.setText("NUEVO");
        jBnuevolibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevolibroActionPerformed(evt);
            }
        });

        jBgrabarlibro.setText("GRABAR");
        jBgrabarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgrabarlibroActionPerformed(evt);
            }
        });

        jBeliminarlibro.setText("ELIMINAR");
        jBeliminarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarlibroActionPerformed(evt);
            }
        });

        jBmodificarlibro.setText("MODIFICAR");
        jBmodificarlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarlibroActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(jTcodigolibro);

        jScrollPane8.setViewportView(jTtitulolibro);

        jScrollPane9.setViewportView(JTautorlibro);

        jScrollPane10.setViewportView(jTpreciolibro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBnuevolibro)
                                .addGap(73, 73, 73)
                                .addComponent(jBgrabarlibro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBeliminarlibro))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                                    .addComponent(jScrollPane8)
                                    .addComponent(jScrollPane9)
                                    .addComponent(jScrollPane10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jBmodificarlibro)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnuevolibro)
                    .addComponent(jBgrabarlibro)
                    .addComponent(jBeliminarlibro)
                    .addComponent(jBmodificarlibro))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Clientes:");

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("ID:");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("NOMBRE:");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("DIRECCION:");

        tablaCliente.setBackground(new java.awt.Color(255, 255, 255));
        tablaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaClienteMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tablaCliente);

        JBagregarCliente.setText("AGREGAR CLIENTE");
        JBagregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBagregarClienteActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(JTIdCliente);

        jScrollPane5.setViewportView(JTnombreCliente);

        jScrollPane6.setViewportView(JTdireccionCliente);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(jScrollPane5)
                                    .addComponent(jScrollPane6)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(JBagregarCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(JBagregarCliente)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ventas:");

        tablaVentas.setBackground(new java.awt.Color(255, 255, 255));
        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaVentasMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVentas);

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("NUMERO VENTA:");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("NOMBRE CLIENTE:");

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("CODIGO LIBRO:");

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("TOTAL PAGAR:");

        jScrollPane11.setViewportView(jTnumeroVenta);

        jScrollPane12.setViewportView(jTnombreCVenta);

        jScrollPane13.setViewportView(jTCodigoLibrov);

        jScrollPane14.setViewportView(jTtotalPVenta);

        jBnuevaVenta.setText("NUEVO");
        jBnuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevaVentaActionPerformed(evt);
            }
        });

        jBgrabarVenta.setText("GRABAR");
        jBgrabarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgrabarVentaActionPerformed(evt);
            }
        });

        JBmodificarVenta.setText("MODIFICAR");
        JBmodificarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmodificarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBnuevaVenta)
                                .addGap(35, 35, 35)
                                .addComponent(jBgrabarVenta)
                                .addGap(49, 49, 49)
                                .addComponent(JBmodificarVenta))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(jScrollPane12)
                                    .addComponent(jScrollPane13)
                                    .addComponent(jScrollPane14))))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnuevaVenta)
                    .addComponent(jBgrabarVenta)
                    .addComponent(JBmodificarVenta))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel1.setText("Bienvenido a la libreria ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(538, 538, 538))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBagregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBagregarClienteActionPerformed
        // TODO add your handling code here:
        DataCliente cliente = new DataCliente();
        cliente.setId(Integer.parseInt(this.JTIdCliente.getText()));
        cliente.setNombreCliente(this.JTnombreCliente.getText());
        cliente.setDireccion(this.JTdireccionCliente.getText());
        JOptionPane.showMessageDialog(null, cliente.GrabarCliente());
        listarcliente();
    }//GEN-LAST:event_JBagregarClienteActionPerformed

    private void jBnuevolibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevolibroActionPerformed
        // TODO add your handling code here:
        limpiarCajasTextoL();
        jBgrabarlibro.setEnabled(true);
    }//GEN-LAST:event_jBnuevolibroActionPerformed

    private void jBgrabarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgrabarlibroActionPerformed
        // TODO add your handling code here:
         DataLibro libro = new DataLibro();
        libro.setCodigo(Integer.parseInt(this.jTcodigolibro.getText()));
        libro.setTitulo(this.jTtitulolibro.getText());
        libro.setAutor(this.JTautorlibro.getText());
        libro.setPrecio(Integer.parseInt(this.jTpreciolibro.getText()));
        JOptionPane.showMessageDialog(null, libro.Grabarlibro());
        listarlibro();
    }//GEN-LAST:event_jBgrabarlibroActionPerformed

    private void jBnuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevaVentaActionPerformed
        // TODO add your handling code here:
        limpiarCajasTextoV();
        jBgrabarVenta.setEnabled(true);
    }//GEN-LAST:event_jBnuevaVentaActionPerformed

    private void jBmodificarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarlibroActionPerformed
        // TODO add your handling code here:
        DataLibro libro = new DataLibro();
        libro.setCodigo(Integer.parseInt(this.jTcodigolibro.getText()));
        libro.setTitulo(this.jTtitulolibro.getText());
        libro.setAutor(this.JTautorlibro.getText());
        libro.setPrecio(Integer.parseInt(this.jTpreciolibro.getText()));
        JOptionPane.showMessageDialog(null,libro.EditarLibro());
        listarlibro();
    }//GEN-LAST:event_jBmodificarlibroActionPerformed

    private void jBeliminarlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarlibroActionPerformed
        // TODO add your handling code here:
         int rec = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el libro? "+ this.jTcodigolibro.getText());
        
        if (rec == 0){
            DataLibro libro1 = new DataLibro();
            libro1.setCodigo(Integer.parseInt(this.jTcodigolibro.getText()));
            JOptionPane.showMessageDialog(null, libro1.EliminarLibro());
            listarlibro();
            JOptionPane.showConfirmDialog(null, "Articulo Eliminado");
        }
    }//GEN-LAST:event_jBeliminarlibroActionPerformed

    private void JBmodificarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmodificarVentaActionPerformed
        // TODO add your handling code here:
        DataVenta venta = new DataVenta();
        venta.setNumeroVenta(Integer.parseInt(this.jTnumeroVenta.getText()));
        venta.setNombreCliente(this.jTnombreCVenta.getText());
        venta.setCodigoLibro(Integer.parseInt(this.jTCodigoLibrov.getText()));
        venta.setTotalPagar(Integer.parseInt(this.jTtotalPVenta.getText()));
        JOptionPane.showMessageDialog(null,venta.EditarVenta());
        listarventa();
    }//GEN-LAST:event_JBmodificarVentaActionPerformed

    private void jBgrabarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgrabarVentaActionPerformed
        // TODO add your handling code here:
         DataVenta venta = new DataVenta();
        venta.setNumeroVenta(Integer.parseInt(this.jTnumeroVenta.getText()));
        venta.setNombreCliente(this.jTnombreCVenta.getText());
        venta.setCodigoLibro(Integer.parseInt(this.jTCodigoLibrov.getText()));
        venta.setTotalPagar(Integer.parseInt(this.jTtotalPVenta.getText()));
        JOptionPane.showMessageDialog(null, venta.GrabarVenta());
        listarventa();
    }//GEN-LAST:event_jBgrabarVentaActionPerformed

    private void tablaClienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClienteMousePressed
        // TODO add your handling code here:
        int rec = this.tablaCliente.getSelectedRow();
        this.JTIdCliente.setText(tablaCliente.getValueAt(rec,0).toString());
        this.JTnombreCliente.setText(tablaCliente.getValueAt(rec,1).toString());
        this.JTdireccionCliente.setText(tablaCliente.getValueAt(rec,2).toString());

    }//GEN-LAST:event_tablaClienteMousePressed

    private void tablaLibrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLibrosMousePressed
        // TODO add your handling code here:
        int rec = this.tablaLibros.getSelectedRow();
        this.jTcodigolibro.setText(tablaLibros.getValueAt(rec,0).toString());
        this.jTtitulolibro.setText(tablaLibros.getValueAt(rec,1).toString());
        this.JTautorlibro.setText(tablaLibros.getValueAt(rec,2).toString());
        this.jTpreciolibro.setText(tablaLibros.getValueAt(rec,3).toString());
    }//GEN-LAST:event_tablaLibrosMousePressed

    private void tablaVentasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentasMousePressed
        // TODO add your handling code here:
        int rec = this.tablaVentas.getSelectedRow();
        this.jTnumeroVenta.setText(tablaVentas.getValueAt(rec,0).toString());
        this.jTnombreCVenta.setText(tablaVentas.getValueAt(rec,1).toString());
        this.jTCodigoLibrov.setText(tablaVentas.getValueAt(rec,2).toString());
        this.jTtotalPVenta.setText(tablaVentas.getValueAt(rec,3).toString());
    }//GEN-LAST:event_tablaVentasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBagregarCliente;
    private javax.swing.JButton JBmodificarVenta;
    private javax.swing.JTextPane JTIdCliente;
    private javax.swing.JTextPane JTautorlibro;
    private javax.swing.JTextPane JTdireccionCliente;
    private javax.swing.JTextPane JTnombreCliente;
    private javax.swing.JButton jBeliminarlibro;
    private javax.swing.JButton jBgrabarVenta;
    private javax.swing.JButton jBgrabarlibro;
    private javax.swing.JButton jBmodificarlibro;
    private javax.swing.JButton jBnuevaVenta;
    private javax.swing.JButton jBnuevolibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextPane jTCodigoLibrov;
    private javax.swing.JTextPane jTcodigolibro;
    private javax.swing.JTextPane jTnombreCVenta;
    private javax.swing.JTextPane jTnumeroVenta;
    private javax.swing.JTextPane jTpreciolibro;
    private javax.swing.JTextPane jTtitulolibro;
    private javax.swing.JTextPane jTtotalPVenta;
    private javax.swing.JTable tablaCliente;
    private javax.swing.JTable tablaLibros;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
