/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CapaPresentacion;
import CapaNegocio.DataLibro;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luanz
 */
public class Formulario extends javax.swing.JFrame {

    public Formulario() {
        initComponents(); // método llamado por el constructor donde se inicializan todos los componentes gráficos
        this.setSize(1100, 500);
        listarLibro();
        grabarB.setEnabled(false);
    }
    
    /**
     * funcion que crea la vista de la tabla en la aplicacion y le pone los elementos de la tabla de la base de datos
     */
    public void listarLibro(){
        DefaultTableModel tabla = new DefaultTableModel();
        DataLibro libro = new DataLibro();
        ArrayList<DataLibro> lista2 = new ArrayList();
        lista2 = libro.ListaLibro();
        tabla.addColumn("Codigo");
        tabla.addColumn("Titulo");
        tabla.addColumn("Cantidad");
        tabla.addColumn("Autor");
        tabla.addColumn("Precio");
        tabla.setRowCount(lista2.size());
        int i=0;
        
        for(DataLibro x: lista2){
            tabla.setValueAt(x.getCodigo(), i, 0);
            tabla.setValueAt(x.getTitulo(), i, 1);
            tabla.setValueAt(x.getCantidad(), i, 2);
            tabla.setValueAt(x.getAutor(), i, 3);
            tabla.setValueAt(x.getPrecio(), i, 4);
            i++;
        }
        this.jTable1.setModel(tabla);
    }
    
    /**
     * Funcion que pone en blanco todas las casillas de texto en la vista
     */
    public void limpiarCajasTexto(){
        this.codigoT.setText("");
        this.tituloT.setText("");
        this.cantidadT.setText("");
        this.AutorT.setText("");
        this.precioT.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        codigoT = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tituloT = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        cantidadT = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        AutorT = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        precioT = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nuevoB = new javax.swing.JButton();
        grabarB = new javax.swing.JButton();
        modificarB = new javax.swing.JButton();
        eliminarB = new javax.swing.JButton();
        salirB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Codigo:");

        jLabel2.setText("Titulo: ");

        jLabel3.setText("Cantidad:");

        jLabel4.setText("Autor:");

        jLabel5.setText("Precio:");

        jScrollPane1.setViewportView(codigoT);

        jScrollPane2.setViewportView(tituloT);

        jScrollPane3.setViewportView(cantidadT);

        jScrollPane4.setViewportView(AutorT);

        jScrollPane5.setViewportView(precioT);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(jTable1);

        nuevoB.setText("Nuevo");
        nuevoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoBActionPerformed(evt);
            }
        });

        grabarB.setText("Grabar");
        grabarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarBActionPerformed(evt);
            }
        });

        modificarB.setText("Modificar");
        modificarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBActionPerformed(evt);
            }
        });

        eliminarB.setText("Eliminar");
        eliminarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBActionPerformed(evt);
            }
        });

        salirB.setText("Salir");
        salirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevoB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grabarB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modificarB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addComponent(eliminarB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salirB)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevoB)
                            .addComponent(grabarB))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modificarB)
                            .addComponent(eliminarB)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(salirB)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * metodo que sirve para ejecutar la accion correspodiente a el boton "nuevo"
     * @param evt 
     */
    private void nuevoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoBActionPerformed
        limpiarCajasTexto();
        grabarB.setEnabled(true);
    }//GEN-LAST:event_nuevoBActionPerformed
    
    /**
     * metodo que sirve para ejecutar la accion correspodiente a el boton "modificar"
     * @param evt 
     */
    private void modificarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBActionPerformed
        DataLibro libro = new DataLibro();
        libro.setCodigo(this.codigoT.getText());
        libro.setTitulo(this.tituloT.getText());
        libro.setCantidad(Integer.parseInt(this.cantidadT.getText()));
        libro.setAutor(this.AutorT.getText());
        libro.setPrecio(Integer.parseInt(this.precioT.getText()));
        JOptionPane.showMessageDialog(null,libro.EditarLibro());
        listarLibro();
    }//GEN-LAST:event_modificarBActionPerformed
    
    /**
     * metodo que sirve para ejecutar la accion correspodiente a el boton "grabar"
     * @param evt 
     */
    private void grabarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarBActionPerformed
        // TODO add your handling code here:
        DataLibro libro = new DataLibro();
        libro.setCodigo(this.codigoT.getText());
        libro.setTitulo(this.tituloT.getText());
        libro.setCantidad(Integer.parseInt(this.cantidadT.getText()));
        libro.setAutor(this.AutorT.getText());
        libro.setPrecio(Integer.parseInt(this.precioT.getText()));
        JOptionPane.showMessageDialog(null, libro.Grabarlibro());
        listarLibro();
    }//GEN-LAST:event_grabarBActionPerformed
    
    /**
     * metodo que sirve para ejecutar la accion correspodiente a el boton "eliminar"
     * @param evt 
     */
    private void eliminarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBActionPerformed
        // TODO add your handling code here:
         int rec = JOptionPane.showConfirmDialog(null, "Esta seguro de eliminar el libro? "+ this.codigoT.getText());
        
        if (rec == 0){
            DataLibro libro1 = new DataLibro();
            libro1.setCodigo(this.codigoT.getText());
            JOptionPane.showMessageDialog(null, libro1.EliminarLibro());
            listarLibro();
            JOptionPane.showConfirmDialog(null, "Articulo Eliminado");
        }
    }//GEN-LAST:event_eliminarBActionPerformed
    
    /**
     * metodo que sirve para ejecutar la accion correspodiente a el boton "salir"
     * @param evt 
     */
    private void salirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(null, "Esta Seguro");
        
        if(r == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_salirBActionPerformed
    
    /**
     * metodo que sirve para darle texto a las casillas de la vista cuando se seleccione un elemento de la tabla
     * @param evt 
     */
    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        // TODO add your handling code here:
        int rec = this.jTable1.getSelectedRow();
        this.codigoT.setText(jTable1.getValueAt(rec,0).toString());
        this.tituloT.setText(jTable1.getValueAt(rec,1).toString());
        this.cantidadT.setText(jTable1.getValueAt(rec,2).toString());
        this.AutorT.setText(jTable1.getValueAt(rec,3).toString());
        this.precioT.setText(jTable1.getValueAt(rec,4).toString());
    }//GEN-LAST:event_jTable1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane AutorT;
    private javax.swing.JTextPane cantidadT;
    private javax.swing.JTextPane codigoT;
    private javax.swing.JButton eliminarB;
    private javax.swing.JButton grabarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificarB;
    private javax.swing.JButton nuevoB;
    private javax.swing.JTextPane precioT;
    private javax.swing.JButton salirB;
    private javax.swing.JTextPane tituloT;
    // End of variables declaration//GEN-END:variables
}
